### ISSUE TITLE
Create Github Pages sphinx documentation

### ISSUE THREAD

**Issue by roelzkie15** [epogrebnyak/weo-reader#24]
Todos:
- [x] generate sphinx documentations in a `site` folder.
- [x] Use `ghp-import` to handle pushing of the documentation to the `gh-pages` branch.
- [x] Create github action workflow to publish documentation in the pipeline.
- [x] Use `rinohtype` to generate pdf version of the documentation.
- [x] Add instruction to justfile to generate pdf documentation version.

**Comment by epogrebnyak** [comment]
Also needs Pages to run

**Comment by epogrebnyak** [comment]
Done creating the the docs pipeline - but the docs content looks aghhh... plenty to improve.

Thanks @roelzkie15 for handling the issue!
