### ISSUE TITLE
WEOJune2020update 

### ISSUE THREAD

**Issue by sebastianvermaas** [epogrebnyak/weo-reader#8]
Base functionality does not support downloading the recent update from the IMF. 

EDIT: Seeing now that the June Update dataset is not in the same format or for all countries. Will leave this open in case there is eventually an update to the source dataset. 

Perhaps something along the lines of:

```python
def to_month(year: int, period: int):
    check_period(period)
    month = {1: "Apr", 2: "Oct"}[period]
    # Second 2011 WEO issue was in September, not October
    if year == 2011 and period == 2:
        month = "Sep"
   # Real GDP outlooks were updated in June
    if year == 2020 and period == 1:
        month = "Jun"

    return month
```

EDIT 2: Closing as this happens frequently and is not specific to this June ..

**Comment by epogrebnyak** [comment]
@sebastianvermaas - maybe I should change the API to `download(year=2019, period='April', path='weo_2019_2.csv', overwrite=True)`.

This way the user gets much more control over what rekease to download.

**Comment by epogrebnyak** [comment]
The June 2020 data is really just one table, unlike a big release.
